version: '3.9'

services:
  database:
    image: postgres:14
    container_name: database
    env_file:
      - .env_db
    networks:
      - back_net
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d rachun_db -U rachun_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: tg_bot
    container_name: backend
    build:
      context: ./tg_bot
      dockerfile: Dockerfile
    networks:
      - back_net
    environment:
      PORT: 5432
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

networks:
  back_net:
    driver: bridge

volumes:
  db: